[build]
  Publish = "src/out"
  Functions = "src/lambda"
  Command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000 ; includeSubDomains"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Service-Worker-Allowed = "/"
