[build]
  Publish = "out"
  Functions = "lambda"
  Command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Service-Worker-Allowed = "/"
